// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Returns 200 OK response",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "responses"
                ],
                "summary": "Shows OK response",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/json": {
            "get": {
                "description": "Returns JSON",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "responses"
                ],
                "summary": "Shows JSON",
                "responses": {}
            }
        },
        "/myproblem": {
            "get": {
                "description": "Returns 500 Internal Server Error",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "responses"
                ],
                "summary": "Shows Internal Server Error",
                "responses": {
                    "500": {
                        "description": "500 Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/yourproblem": {
            "get": {
                "description": "Returns 400 Bad Request response",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "responses"
                ],
                "summary": "Shows bad request response",
                "responses": {
                    "400": {
                        "description": "400 Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "HTTP From TCP API",
	Description:      "API para manejo de peticiones HTTP personalizadas",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
